// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace FIGameplayTags
{
	FATEIRONPRO_API	FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);

	// Declare all of the custom native tags that Lyra will use
	FATEIRONPRO_API 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_IsDead);
	FATEIRONPRO_API 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cooldown);
	FATEIRONPRO_API 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cost);
	FATEIRONPRO_API 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsBlocked);
	FATEIRONPRO_API 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsMissing);
	FATEIRONPRO_API 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Networking);
	FATEIRONPRO_API 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_ActivationGroup);

	FATEIRONPRO_API 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Behavior_SurvivesDeath);

	FATEIRONPRO_API 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	FATEIRONPRO_API 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	FATEIRONPRO_API 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Stick);
	FATEIRONPRO_API 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	FATEIRONPRO_API 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_AutoRun);

	FATEIRONPRO_API 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_Spawned);
	FATEIRONPRO_API 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataAvailable);
	FATEIRONPRO_API 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataInitialized);
	FATEIRONPRO_API 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_GameplayReady);

	FATEIRONPRO_API 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Death);
	FATEIRONPRO_API 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Reset);
	FATEIRONPRO_API 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_RequestReset);

	FATEIRONPRO_API 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Damage);
	FATEIRONPRO_API 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Heal);

	FATEIRONPRO_API 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_GodMode);
	FATEIRONPRO_API 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_UnlimitedHealth);

	FATEIRONPRO_API 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Crouching);
	FATEIRONPRO_API 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_AutoRunning);
	FATEIRONPRO_API 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death);
	FATEIRONPRO_API 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dying);
	FATEIRONPRO_API 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dead);

	// These are mappings from MovementMode enums to GameplayTags associated with those enums (below)
	FATEIRONPRO_API 	extern const TMap<uint8, FGameplayTag> MovementModeTagMap;
	FATEIRONPRO_API 	extern const TMap<uint8, FGameplayTag> CustomMovementModeTagMap;

	FATEIRONPRO_API 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Walking);
	FATEIRONPRO_API 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_NavWalking);
	FATEIRONPRO_API 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Falling);
	FATEIRONPRO_API 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Swimming);
	FATEIRONPRO_API 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Flying);

	FATEIRONPRO_API 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Custom);
};
